# Generated by Django 4.1.7 on 2023-03-28 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikiTranslate', '0002_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wikiTranslate.project'),
        ),
    ]
