# Generated by Django 4.1.7 on 2023-03-29 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikiTranslate', '0003_alter_sentence_project_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('articleTitle', 'target_lang')},
        ),
    ]
