# Generated by Django 4.1.7 on 2023-03-30 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikiTranslate', '0005_alter_project_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('articleTitle', 'target_lang')},
        ),
    ]
