# Generated by Django 4.1.7 on 2023-03-30 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikiTranslate', '0006_alter_project_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='target_lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wikiTranslate.targetlang', verbose_name='Target Language'),
        ),
        migrations.AlterUniqueTogether(
            name='sentence',
            unique_together={('project_id', 'original_sentence')},
        ),
    ]
